import type { Metadata } from "next";
import { Inter, Rubik, Chivo } from "next/font/google";
import "./globals.css";

export const rubik = Rubik({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-rubik",
});
export const chivo = Chivo({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-chivo",
});
export const inter = Inter({
	subsets: ["latin"],
	display: "swap",
	variable: "--font-inter",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={inter.className}>{children}</body>
		</html>
	);
}
