"use client";

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/nbHwq2SxklA
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

interface Props {
	messages: Array<{
		author: string;
		message: string;
	}>;
}

export function ChatBox({ messages }: Props) {
	return (
		<section className="bg-white flex flex-col h-full dark:bg-gray-950 flex-1  shadow-lg w-full p-6">
			<div className="space-y-4 flex-1 overflow-y-auto">
				{messages.map(({ author, message }, index) => (
					<div
						key={`${message}-${index}-${author}`}
						className="flex items-start gap-4"
					>
						<div className="rounded-full bg-gray-200 dark:bg-gray-800 w-8 h-8 flex items-center justify-center text-gray-600 dark:text-gray-400 font-medium">
							{author.split("")[0]}
						</div>
						<div className="space-y-1">
							<div className="font-medium text-gray-900 dark:text-gray-100">
								{author}
							</div>
							<div className="text-gray-600 dark:text-gray-400 text-sm">
								{message}
							</div>
						</div>
					</div>
				))}
			</div>
			<div className="mt-6 border-t border-gray-200 dark:border-gray-800 pt-4">
				<div className="relative">
					<input
						className="w-full outline-none transition-all bg-gray-100 dark:bg-gray-800 border focus:ring-0 rounded-lg px-4 py-2 text-gray-900 dark:text-gray-100 placeholder-gray-500 dark:placeholder-gray-400 dark:border-gray-800 border-gray-200 dark:hover:border-gray-500 hover:border-gray-300 dark:focus:border-gray-500 focus:border-gray-300"
						placeholder="Type your message..."
						type="text"
					/>
					<button
						type="submit"
						className="absolute right-2 top-1/2 -translate-y-1/2 text-gray-500 dark:text-gray-400 hover:text-gray-900 dark:hover:text-gray-100"
					>
						{/* biome-ignore lint/a11y/noSvgWithoutTitle: <explanation> */}
						<svg
							className="h-5 w-5"
							fill="none"
							stroke="currentColor"
							viewBox="0 0 24 24"
							xmlns="http://www.w3.org/2000/svg"
						>
							<path
								d="M12 19l9 2-9-18-9 18 9-2zm0 0v-8"
								strokeLinecap="round"
								strokeLinejoin="round"
								strokeWidth={2}
							/>
						</svg>
					</button>
				</div>
			</div>
		</section>
	);
}
