/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/i1L12ZDHqf1
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
import {
	CollapsibleTrigger,
	CollapsibleContent,
	Collapsible,
} from "@/components/ui/collapsible";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { LoginButton } from "./home-page/login-button";

export function HomePage() {
	return (
		<main>
			<section className="w-full py-12 md:py-24 lg:py-32 flex flex-col justify-center items-center">
				<div className="container space-y-10 xl:space-y-16">
					<div className="flex flex-col items-center space-y-4 text-center">
						<div className="space-y-2">
							<h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl/none">
								UnifyBot
							</h1>
							<p className="mx-auto max-w-[700px] text-gray-500 md:text-xl dark:text-gray-400">
								A powerful and customizable Twitch bot to enhance your stream.
							</p>
						</div>
						<div className="flex gap-4">
							<LoginButton />
						</div>
					</div>
				</div>
			</section>
			<section className="w-full py-12 md:py-24 lg:py-32 bg-gray-100 dark:bg-gray-800 flex flex-col justify-center items-center">
				<div className="container grid items-center gap-6 lg:grid-cols-[1fr_500px] lg:gap-12 xl:grid-cols-[1fr_550px]">
					<div className="flex flex-col justify-center space-y-4">
						<div className="space-y-2">
							<div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
								Features
							</div>
							<h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
								Powerful Features for Your Stream
							</h2>
							<p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
								Our Unify bot offers a wide range of features to enhance your
								streaming experience and engage your audience.
							</p>
						</div>
						<div className="grid grid-cols-2 gap-6">
							<div className="space-y-2">
								<h3 className="text-lg font-bold">Moderation</h3>
								<p className="text-sm text-gray-500 dark:text-gray-400">
									Automatically moderate your chat and keep your community safe.
								</p>
							</div>
							<div className="space-y-2">
								<h3 className="text-lg font-bold">Alerts</h3>
								<p className="text-sm text-gray-500 dark:text-gray-400">
									Customize your alerts to celebrate new followers, subscribers,
									and more.
								</p>
							</div>
							<div className="space-y-2">
								<h3 className="text-lg font-bold">Commands</h3>
								<p className="text-sm text-gray-500 dark:text-gray-400">
									Allow your viewers to interact with your bot using custom
									commands.
								</p>
							</div>
							<div className="space-y-2">
								<h3 className="text-lg font-bold">Analytics</h3>
								<p className="text-sm text-gray-500 dark:text-gray-400">
									Track your stream metrics and viewer engagement with detailed
									analytics.
								</p>
							</div>
						</div>
					</div>

					<iframe
						title="Twitch Player"
						// TODO: Replace parent with the actual parent URL
						src="https://player.twitch.tv/?channel=akozl&parent="
						allowFullScreen
						className="mx-auto aspect-video overflow-hidden rounded-xl object-cover object-center sm:w-full lg:order-last"
						height="310"
						width="550"
					/>
				</div>
			</section>
			<section className="w-full py-12 md:py-24 lg:py-32 flex flex-col justify-center items-center">
				<div className="container space-y-8">
					<div className="flex flex-col items-center space-y-4 text-center">
						<div className="space-y-2">
							<div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
								Commands
							</div>
							<h2 className="text-3xl font-bold tracking-tighter sm:text-5xl">
								Explore Our Commands
							</h2>
							<p className="max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
								Our Unify bot offers a wide range of commands to enhance your
								streaming experience and engage your audience.
							</p>
						</div>
					</div>
					<Collapsible className="rounded-lg border border-gray-200 bg-white shadow-sm  dark:bg-gray-950 dark:border-gray-800">
						<CollapsibleTrigger className="flex w-full items-center justify-between gap-4 border-b px-6 py-4 text-lg font-medium dark:border-gray-800">
							<span>Commands</span>
							<ChevronDownIcon className="h-5 w-5 transition-transform [&[data-state=open]]:rotate-180" />
						</CollapsibleTrigger>
						<CollapsibleContent className="space-y-4 p-6">
							<div className="space-y-2">
								<h3 className="text-lg font-bold">Moderation Commands</h3>
								<div className="grid grid-cols-2 gap-4 text-sm">
									<div>
										<span className="font-medium">!ban</span>- Ban a user from
										the chat
									</div>
									<div>
										<span className="font-medium">!timeout</span>- Timeout a
										user for a specified duration
									</div>
									<div>
										<span className="font-medium">!purge</span>- Remove all
										messages from a user
									</div>
									<div>
										<span className="font-medium">!slowmode</span>- Enable or
										disable slowmode
									</div>
								</div>
							</div>
							<div className="space-y-2">
								<h3 className="text-lg font-bold">Interaction Commands</h3>
								<div className="grid grid-cols-2 gap-4 text-sm">
									<div>
										<span className="font-medium">!uptime</span>- Check how long
										the stream has been live
									</div>
									<div>
										<span className="font-medium">!game</span>- Display the
										current game being played
									</div>
									<div>
										<span className="font-medium">!title</span>- Display the
										current stream title
									</div>
									<div>
										<span className="font-medium">!socials</span>- Show the
										{"streamer's"} social media links
									</div>
								</div>
							</div>
							<div className="space-y-2">
								<h3 className="text-lg font-bold">Fun Commands</h3>
								<div className="grid grid-cols-2 gap-4 text-sm">
									<div>
										<span className="font-medium">!dice</span>- Roll a random
										number
									</div>
									<div>
										<span className="font-medium">!8ball</span>- Get a random
										answer from the Magic 8 Ball
									</div>
									<div>
										<span className="font-medium">!joke</span>- Tell a random
										joke
									</div>
									<div>
										<span className="font-medium">!quote</span>- Display a
										random inspirational quote
									</div>
								</div>
							</div>
						</CollapsibleContent>
					</Collapsible>
				</div>
			</section>
			<section className="w-full py-12 md:py-24 lg:py-32 border-t flex flex-col justify-center items-center">
				<div className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
					<div className="space-y-3">
						<div className="inline-block rounded-lg bg-gray-100 px-3 py-1 text-sm dark:bg-gray-800">
							Contact
						</div>
						<h2 className="text-3xl font-bold tracking-tighter md:text-4xl/tight">
							Get in Touch
						</h2>
						<p className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
							Have a question or need help with our Unify bot? Fill out the form
							below and {"we'll"} get back to you as soon as possible.
						</p>
					</div>
					<form className="mx-auto w-full max-w-sm space-y-4">
						<div className="grid grid-cols-2 gap-4">
							<div className="space-y-2">
								<Label htmlFor="name">Name</Label>
								<Input id="name" placeholder="Enter your name" />
							</div>
							<div className="space-y-2">
								<Label htmlFor="email">Email</Label>
								<Input id="email" placeholder="Enter your email" type="email" />
							</div>
						</div>
						<div className="space-y-2">
							<Label htmlFor="message">Message</Label>
							<Textarea
								className="min-h-[100px]"
								id="message"
								placeholder="Enter your message"
							/>
						</div>
						<Button className="w-full" type="submit">
							Submit
						</Button>
					</form>
				</div>
			</section>
		</main>
	);
}

function ChevronDownIcon(props: React.SVGProps<SVGSVGElement>) {
	return (
		// biome-ignore lint/a11y/noSvgWithoutTitle: <explanation>
		<svg
			{...props}
			xmlns="http://www.w3.org/2000/svg"
			width="24"
			height="24"
			viewBox="0 0 24 24"
			fill="none"
			stroke="currentColor"
			strokeWidth="2"
			strokeLinecap="round"
			strokeLinejoin="round"
		>
			<path d="m6 9 6 6 6-6" />
		</svg>
	);
}
