/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/nRFlDhWlykJ
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

import { TwitchIcon } from "./dashboard-page";

export function ValidatingTwitchLoader() {
	return (
		<div className="flex h-screen w-full items-center justify-center bg-gray-100 dark:bg-gray-950">
			<div className="text-center flex flex-col gap-12 items-center">
				<h1 className="text-4xl font-bold text-gray-900 dark:text-gray-50 flex items-center gap-2">
					<TwitchIcon className="size-9" />
					Validating Twitch Account
				</h1>
				<div className="inline-block animate-spin rounded-full border-4 border-purple-500 border-t-transparent h-12 w-12 mb-4" />
			</div>
		</div>
	);
}
